apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "warpdrive.fullname" . }}-agent
  labels:
    {{- include "warpdrive.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "warpdrive.fullname" . }}-agent
subjects:
  - kind: ServiceAccount
    name: {{ include "warpdrive.fullname" . }}-agent
    namespace: {{ .Release.Namespace }}
