{{- if .Values.pdb.enabled }}
{{- if .Values.controlPlane.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "warpdrive.fullname" . }}-control
  labels:
    {{- include "warpdrive.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      app: warpdrive-control
      {{- include "warpdrive.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
