{{- if .Values.controlPlane.database.passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warpdrive.fullname" . }}-secrets
  labels:
    {{- include "warpdrive.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.controlPlane.database.password | default "" | b64enc | quote }}
{{- end }}
